<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MegaplanSync.ApiClient\MegaplanSync.ApiClient.csproj" />
    <ProjectReference Include="..\MegaplanSync.Core\MegaplanSync.Core.csproj" />
    <ProjectReference Include="..\MegaplanSync.DataAccess.MySql\MegaplanSync.DataAccess.MySql.csproj" />
    <ProjectReference Include="..\MegaplanSync.Logging\MegaplanSync.Logging.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="..\Resources\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.9" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
	</ItemGroup>

</Project>
